# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('car_number', models.CharField(max_length=20)),
                ('car_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=1000)),
                ('wrong_answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiCall',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(default=0)),
                ('IsMap', models.BooleanField(default=False)),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('address', models.CharField(default='None', max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('details', models.CharField(default='None', max_length=500)),
                ('call_time', models.TimeField(auto_now=True)),
                ('status', models.CharField(default='new', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxibot.TaxiCall'),
        ),
    ]
