# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_number',
            field=models.CharField(default='недоступен', max_length=30),
        ),
    ]
