# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0003_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicall',
            name='waiting_for',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='taxicall',
            name='number',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxicall',
            name='type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
