# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0002_car_driver_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
